export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const LOGIN_GET_LOADING = "LOGIN_GET_LOADING";
export const LOGIN_GET_SUCCESS = "LOGIN_GET_SUCCESS";
export const LOGIN_GET_ERROR = "LOGIN_GET_ERROR";
export const LOGOUT_GET = "LOGOUT_GET";

export const UPDATE_GET_FAILED = "UPDATE_GET_FAILED";
export const UPDATE_GET_SUCCESS = "UPDATE_GET_SUCCESS";
export const UPDATE_GET_REQUEST = "UPDATE_GET_REQUEST";

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE';