export const BLOG_GET_ALL_FAILURES = "BLOG_GET_ALL_FAILURES";
export const BLOG_GET_ALL_SUCCESS = "BLOG_GET_ALL_SUCCESS";
export const BLOG_GET_ALL_REQUEST = "BLOG_GET_ALL_REQUEST";

export const BLOG_GET_DETAIL_FAILURE = "BLOG_GET_DETAIL_FAILURE";
export const BLOG_GET_DETAIL_SUCCESS = "BLOG_GET_DETAIL_SUCCESS";
export const BLOG_GET_DETAIL_REQUEST = "BLOG_GET_DETAIL_REQUEST";

export const BLOG_CATEGORY_GET_ALL_REQUEST = "BLOG_CATEGORY_GET_ALL_REQUEST";
export const BLOG_CATEGORY_GET_ALL_SUCCESS = "BLOG_CATEGORY_GET_ALL_SUCCESS";
export const BLOG_CATEGORY_GET_ALL_FAILURES = "BLOG_CATEGORY_GET_ALL_FAILURES";