export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAILURE = 'BRAND_LIST_FAILURE';

export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST';
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS';
export const BRAND_DETAILS_FAILURE = 'BRAND_DETAILS_FAILURE';