export const CREATE_ODER_FAILURE = 'CREATE_ODER_FAILURE';
export const CREATE_ODER_REQUEST = 'CREATE_ODER_REQUEST';
export const CREATE_ODER_SUCCESS = 'CREATE_ODER_SUCCESS';
export const CREATE_ODER_RESET = 'CREATE_ODER_RESET';
