export const CREATE_ODER_FAILURE = 'CREATE_ODER_FAILURE';
export const CREATE_ODER_REQUEST = 'CREATE_ODER_REQUEST';
export const CREATE_ODER_SUCCESS = 'CREATE_ODER_SUCCESS';
export const CREATE_ODER_RESET = 'CREATE_ODER_RESET';

export const GET_ODER_FAILURE = 'GET_ODER_FAILURE';
export const GET_ODER_REQUEST = 'GET_ODER_REQUEST';
export const GET_ODER_SUCCESS = 'GET_ODER_SUCCESS';
export const GET_ODER_RESET = 'GET_ODER_RESET';

export const CANCEL_ODER_FAILURE = 'CANCEL_ODER_FAILURE';
export const CANCEL_ODER_REQUEST = 'CANCEL_ODER_REQUEST';
export const CANCEL_ODER_SUCCESS = 'CANCEL_ODER_SUCCESS';