
export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAILURE = 'REVIEW_ADD_FAILURE';

export const REVIEW_GET_REQUEST = 'REVIEW_GET_REQUEST';
export const REVIEW_GET_SUCCESS = 'REVIEW_GET_SUCCESS';
export const REVIEW_GET_FAILURE = 'REVIEW_GET_FAILURE';